# Generated by Django 3.1.7 on 2021-08-14 02:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=1000)),
                ('call', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='freelance',
            field=models.CharField(choices=[('Available', 'Available'), ('Currently not available', 'Currently not available')], default='Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='desc2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='desc3',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='desc4',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='desc5',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
