# Generated by Django 3.1.7 on 2021-08-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20210814_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='project_code',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
