# Generated by Django 4.0.2 on 2022-02-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_portfoliopage_project_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('animationText', models.CharField(max_length=255)),
                ('fb_url', models.CharField(default='', max_length=1000)),
                ('insta_url', models.CharField(default='', max_length=1000)),
                ('twitter_url', models.CharField(default='', max_length=1000)),
                ('discord_url', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
