# Generated by Django 4.0.2 on 2022-02-24 20:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_landingpage_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor.fields.RichTextField()),
                ('collection_title', models.CharField(max_length=255)),
                ('collection_desc', ckeditor.fields.RichTextField()),
                ('items', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=1000)),
                ('floor_price', models.CharField(max_length=15)),
                ('volume_traded', models.CharField(max_length=100)),
                ('twitter_url', models.IntegerField()),
                ('opensea_url', models.CharField(max_length=100)),
                ('end_desc', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, upload_to='media/about/')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
