# Generated by Django 4.0.2 on 2022-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_collectionsinfo_delete_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsinfo',
            name='floor_price',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='items',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='opensea_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='twitter_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='volume_traded',
            field=models.CharField(max_length=1000),
        ),
    ]
