# Generated by Django 4.0.2 on 2022-03-06 17:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_alter_collectionsinfo_floor_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsinfo',
            name='floor_price',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='items',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='opensea_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='owner',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='collectionsinfo',
            name='volume_traded',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='skill_desc',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
