# Generated by Django 4.0.2 on 2022-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_collection_journey_mycontact_ourcollection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionsinfo',
            old_name='collection_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='collectionsinfo',
            old_name='collection_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='discord_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='insta_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='linktree_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='opensea_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='twitter_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
