# Generated by Django 4.0.2 on 2022-03-08 16:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_rename_collection_desc_collectionsinfo_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='collection',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
