# Generated by Django 4.0.2 on 2022-03-08 16:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_rename_collection_title_collection_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
