# Generated by Django 4.0.2 on 2022-03-08 16:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_alter_collection_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
