# Generated by Django 4.0.2 on 2022-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0013_alter_collectionsinfo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsinfo',
            name='photo',
            field=models.ImageField(upload_to='media/about/'),
        ),
    ]
