# Generated by Django 4.0.3 on 2022-03-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_alter_collectionsinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcollection',
            name='img_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ourcollection',
            name='opensea_link',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
    ]
