# Generated by Django 4.0.3 on 2022-03-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_alter_ourcollection_img_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/about/'),
        ),
    ]
