# Generated by Django 4.0.3 on 2022-03-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0016_landingpage_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='photo',
        ),
    ]
