# Generated by Django 4.0.3 on 2022-03-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_remove_landingpage_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
