# Generated by Django 4.0.3 on 2022-03-10 11:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0018_remove_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcollection',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
