# Generated by Django 4.0.3 on 2022-03-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0019_ourcollection_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourcollection',
            name='img_link',
        ),
    ]
