# Generated by Django 4.0.3 on 2022-03-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0020_remove_ourcollection_img_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='your_email',
            new_name='email',
        ),
    ]
