# Generated by Django 4.0.3 on 2022-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0022_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1500),
        ),
    ]
