# Generated by Django 4.0.3 on 2022-03-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0025_alter_contact_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
