# Generated by Django 4.0.3 on 2022-03-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0026_remove_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_of_contact',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
