# Generated by Django 4.0.3 on 2022-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0027_contact_date_of_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='animationText2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
