# Generated by Django 4.0.3 on 2022-03-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0028_landingpage_animationtext2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='animationText2',
        ),
    ]
