# Generated by Django 4.0.3 on 2022-03-15 06:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0031_alter_roadmap_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='desc',
        ),
    ]
